name: pepper_cloud_task_manager
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # Networking
  dio: ^5.9.0

  # Local Persistence
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Routing
  go_router: ^16.2.1

  # Dependency Injection
  get_it: ^8.2.0

  dartz: ^0.10.1
  equatable: ^2.0.7
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

flutter:


  
  uses-material-design: true

  assets:
    - assets/app_logo.png
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
